app_category:
    type: dany
    defaults:
        dany:
            dany_resource: app.category
            path: /categories
#        request:
#            query:
#                name:
#                    type: string
#                    enforce: mandatory
#                start:
#                    type: date
#                    format: 'Y-m-d'
#                end:
#                    type: date
#                    format: 'Y-m-d'
#        response:
#            type: json


